[package]
name = "serviceos-shell-service"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "serviceos-shell-service"
path = "src/main.rs"

[dependencies]
serviceos-abi = { path = "../../../shared/abi" }
serviceos-account-service = { path = "../account-service" }
serviceos-peripheral-service = { path = "../peripheral-service" }
serviceos-userspace-runtime = { path = "../runtime" }
