[workspace]
resolver = "3"
members = [
    "shared/abi",
    "shared/bundle",
    "shared/crypto",
    "shared/wireless",
    "kernel/core",
    "arch/x86_64",
    "arch/aarch64",
    "arch/riscv64",
    "platform/x86_64/qemu_virtio",
    "platform/aarch64/raspi5",
    "platform/x86_64/qemu_virtio/image",
    "platform/aarch64/raspi5/image",
    "platform/x86_64/qemu_isa",
    "platform/x86_64/qemu_isa/image",
    "platform/aarch64/virt",
    "platform/aarch64/virt/image",
    "platform/riscv64/virt",
    "platform/riscv64/virt/image",
    "support/xtask-core",
    "support/xtask",
    "userspace/catalog",
    "tests/framework",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Paul H"]
repository = "https://github.com/Superbro525Alt/ServiceOS"
rust-version = "1.85"

[profile.dev]
opt-level = 1
panic = "abort"

[profile.release]
panic = "abort"
