[target.x86_64-unknown-none]
rustflags = [
    "-C",
    "code-model=large",
    "-C",
    "link-arg=-Tlink.ld",
    "-C",
    "link-arg=--gc-sections",
]

[target.aarch64-unknown-none-softfloat]
rustflags = [
    "-C",
    "link-arg=-Tlink.ld",
    "-C",
    "link-arg=--gc-sections",
]

