[package]
name = "serviceos-network-service"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "serviceos-network-service"
path = "src/main.rs"

[dependencies]
serviceos-userspace-runtime = { path = "../runtime" }
smoltcp = { version = "0.12", default-features = false, features = ["medium-ethernet", "proto-ipv4", "socket-icmp", "socket-dhcpv4", "socket-dns", "socket-tcp", "socket-udp"] }
