[workspace]
resolver = "3"
members = [
    "runtime",
    "ui",
    "root-manager",
    "storage-service",
    "log-service",
    "config-service",
    "console-service",
    "graphics-service",
    "status-service",
    "package-service",
    "network-service",
    "audio-service",
    "clipboard-service",
    "security-service",
    "runtime-service",
    "developer-service",
    "session-service",
    "desktop-shell-service",
    "shell-service",
    "settings-app",
    "files-app",
    "media-app",
    "setup-wizard",
    "monitor-app",
    "terminal-service",
    "terminal-app",
    "software-center-app",
    "announce-service",
    "posix-host-tool",
    "cross-builder-tool",
    "sysinfo-tool",
    "account-service",
    "backup-service",
    "power-service",
    "peripheral-service",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
