[workspace]
resolver = "3"
members = [
    "runtime",
    "root-manager",
    "storage-service",
    "log-service",
    "config-service",
    "console-service",
    "graphics-service",
    "status-service",
    "package-service",
    "network-service",
    "session-service",
    "shell-service",
    "announce-service",
    "sysinfo-tool",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
