[workspace]
resolver = "3"
members = [
    "runtime",
    "ui",
    "root-manager",
    "storage-service",
    "log-service",
    "config-service",
    "console-service",
    "graphics-service",
    "status-service",
    "package-service",
    "network-service",
    "session-service",
    "desktop-shell-service",
    "shell-service",
    "settings-app",
    "files-app",
    "monitor-app",
    "terminal-service",
    "terminal-app",
    "announce-service",
    "sysinfo-tool",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
