pub(crate) struct Program {
    pub(crate) package: &'static str,
    pub(crate) bin_name: &'static str,
    pub(crate) image_id: u32,
    pub(crate) service_path: &'static str,
    pub(crate) service_id: u32,
}

pub(crate) const PROGRAMS: &[Program] = &[
    Program {
        package: "serviceos-root-service-manager",
        bin_name: "serviceos-root-service-manager",
        image_id: 1,
        service_path: "services/root-manager/program.img",
        service_id: 1,
    },
    Program {
        package: "serviceos-storage-service",
        bin_name: "serviceos-storage-service",
        image_id: 2,
        service_path: "services/storage-service/program.img",
        service_id: 2,
    },
    Program {
        package: "serviceos-console-service",
        bin_name: "serviceos-console-service",
        image_id: 3,
        service_path: "services/console-service/program.img",
        service_id: 3,
    },
    Program {
        package: "serviceos-config-service",
        bin_name: "serviceos-config-service",
        image_id: 4,
        service_path: "services/config-service/program.img",
        service_id: 4,
    },
    Program {
        package: "serviceos-log-service",
        bin_name: "serviceos-log-service",
        image_id: 5,
        service_path: "services/log-service/program.img",
        service_id: 5,
    },
    Program {
        package: "serviceos-status-service",
        bin_name: "serviceos-status-service",
        image_id: 6,
        service_path: "services/status-service/program.img",
        service_id: 6,
    },
    Program {
        package: "serviceos-shell-service",
        bin_name: "serviceos-shell-service",
        image_id: 7,
        service_path: "services/shell-service/program.img",
        service_id: 7,
    },
    Program {
        package: "serviceos-sysinfo-tool",
        bin_name: "serviceos-sysinfo-tool",
        image_id: 8,
        service_path: "tools/sysinfo-tool/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-package-service",
        bin_name: "serviceos-package-service",
        image_id: 9,
        service_path: "services/package-service/program.img",
        service_id: 8,
    },
    Program {
        package: "serviceos-announce-service",
        bin_name: "serviceos-announce-service",
        image_id: 10,
        service_path: "services/announce-service/program.img",
        service_id: 9,
    },
    Program {
        package: "serviceos-network-service",
        bin_name: "serviceos-network-service",
        image_id: 11,
        service_path: "services/network-service/program.img",
        service_id: 10,
    },
    Program {
        package: "serviceos-audio-service",
        bin_name: "serviceos-audio-service",
        image_id: 20,
        service_path: "services/audio-service/program.img",
        service_id: 15,
    },
    Program {
        package: "serviceos-runtime-service",
        bin_name: "serviceos-runtime-service",
        image_id: 21,
        service_path: "services/runtime-service/program.img",
        service_id: 16,
    },
    Program {
        package: "serviceos-developer-service",
        bin_name: "serviceos-developer-service",
        image_id: 23,
        service_path: "services/developer-service/program.img",
        service_id: 17,
    },
    Program {
        package: "serviceos-clipboard-service",
        bin_name: "serviceos-clipboard-service",
        image_id: 25,
        service_path: "services/clipboard-service/program.img",
        service_id: 18,
    },
    Program {
        package: "serviceos-security-service",
        bin_name: "serviceos-security-service",
        image_id: 27,
        service_path: "services/security-service/program.img",
        service_id: 19,
    },
    Program {
        package: "serviceos-graphics-service",
        bin_name: "serviceos-graphics-service",
        image_id: 12,
        service_path: "services/graphics-service/program.img",
        service_id: 11,
    },
    Program {
        package: "serviceos-session-service",
        bin_name: "serviceos-session-service",
        image_id: 13,
        service_path: "services/session-service/program.img",
        service_id: 12,
    },
    Program {
        package: "serviceos-desktop-shell-service",
        bin_name: "serviceos-desktop-shell-service",
        image_id: 14,
        service_path: "services/desktop-shell-service/program.img",
        service_id: 13,
    },
    Program {
        package: "serviceos-settings-app",
        bin_name: "serviceos-settings-app",
        image_id: 15,
        service_path: "apps/settings-app/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-files-app",
        bin_name: "serviceos-files-app",
        image_id: 16,
        service_path: "apps/files-app/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-monitor-app",
        bin_name: "serviceos-monitor-app",
        image_id: 17,
        service_path: "apps/monitor-app/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-terminal-service",
        bin_name: "serviceos-terminal-service",
        image_id: 18,
        service_path: "services/terminal-service/program.img",
        service_id: 14,
    },
    Program {
        package: "serviceos-terminal-app",
        bin_name: "serviceos-terminal-app",
        image_id: 19,
        service_path: "apps/terminal-app/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-media-app",
        bin_name: "serviceos-media-app",
        image_id: 31,
        service_path: "apps/media-app/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-software-center-app",
        bin_name: "serviceos-software-center-app",
        image_id: 26,
        service_path: "apps/software-center-app/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-posix-host-tool",
        bin_name: "serviceos-posix-host-tool",
        image_id: 22,
        service_path: "tools/posix-host-tool/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-cross-builder-tool",
        bin_name: "serviceos-cross-builder-tool",
        image_id: 24,
        service_path: "tools/cross-builder-tool/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-account-service",
        bin_name: "serviceos-account-service",
        image_id: 28,
        service_path: "services/account-service/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-backup-service",
        bin_name: "serviceos-backup-service",
        image_id: 29,
        service_path: "services/backup-service/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-power-service",
        bin_name: "serviceos-power-service",
        image_id: 30,
        service_path: "services/power-service/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-peripheral-service",
        bin_name: "serviceos-peripheral-service",
        image_id: 34,
        service_path: "services/peripheral-service/program.img",
        service_id: 0,
    },
    Program {
        package: "serviceos-setup-wizard",
        bin_name: "serviceos-setup-wizard",
        image_id: 33,
        service_path: "services/setup-wizard/program.img",
        service_id: 20,
    },
];
