[package]
name = "serviceos-kernel-x86_64"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "serviceos-kernel-x86_64"
path = "src/main.rs"
test = false
bench = false

[dependencies]
serviceos-abi = { path = "../../../../shared/abi" }
serviceos-bundle = { path = "../../../../shared/bundle" }
serviceos-kernel-arch-x86_64 = { path = "../../../../arch/x86_64" }
serviceos-kernel-core = { path = "../../../../kernel/core" }
serviceos-platform-qemu-virtio = { path = ".." }
serviceos-platform-x86-pc = { path = "../../pc" }
spin = "0.9"
uefi = { version = "0.33", default-features = false }
