[package]
name = "serviceos-platform-virt"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
test = false
bench = false

[dependencies]
fdt = "0.2.0-alpha1"
serviceos-abi = { path = "../../../shared/abi" }
serviceos-kernel-core = { path = "../../../kernel/core" }
serviceos-kernel-arch-aarch64 = { path = "../../../arch/aarch64" }
spin = "0.9"
virtio-drivers = { version = "0.13", default-features = false, features = ["alloc"] }
