[package]
name = "serviceos-root-service-manager"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "serviceos-root-service-manager"
path = "src/main.rs"

[dependencies]
serviceos-abi = { path = "../../../shared/abi" }
serviceos-bundle = { path = "../../../shared/bundle" }
serviceos-desktop-ui = { path = "../ui" }
serviceos-userspace-runtime = { path = "../runtime" }
